[package]
name = "gitp2p-sync"
description = "Synchronization sessions, replication, and transport for gitp2p"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gitp2p-metadata = { workspace = true }
gitp2p-trust = { workspace = true }
gitp2p-vault = { workspace = true }
mdns-sd = { workspace = true }
tokio = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
rcgen = { workspace = true }
base64 = { workspace = true }
