[package]
name = "gitp2p-lineage"
description = "gitp2p lineage subsystem"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gitp2p-metadata = { workspace = true }
gitp2p-trust = { workspace = true }
gitp2p-vault = { workspace = true }
sha2 = { workspace = true }
